# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'RestKit'
pod 'ReactiveCocoa'
pod 'SVProgressHUD'
pod 'CCARadialGradientLayer', :git => 'https://github.com/jilouc/CCARadialGradientLayer.git'
